### PR TITLE
Update constants.py

### PR DESCRIPTION
**Pull request by JoyMonteiro**
Added some new constants, taken from the NIST database. Also, changed the name of SB to add constant at the end, to make it consistent with all other "constants".

### CODE REVIEW

**Comment by mcgibbon** [comment]
Should there be a seconds_per_day constant, when there is already a planetary_rotation_rate constant (in days/rotations per second)? I would think not, since a user would expect modifying one to modify the other, but that's not the case unless we do some fancy dictionary subclassing on the default_constants dictionary. Other than that everything looks good.

**Comment by JoyMonteiro** [comment]
2*pi/planetary_rotation_rate does not give the expected 86400 seconds, which is apparently something called a *mean solar day*. Deriving duration of day from planetary rotation seems quite involved because of eccentricity and obliquity:
https://en.wikipedia.org/wiki/Equation_of_time

Therefore, it might help to have it around.

**Comment by mcgibbon** [comment]
The correct expression is 2*pi/planetary_rotation_rate*365.25/364.25 (to account for Earth rotating around the sun, since planetary rotation rate is in an inertial frame of reference), and this gives a very close 86400.71 seconds if you use a more precise value of 7.29211e-5 radians/second for the planetary rotation rate (almost accurate up to the number of sig figs).

But I suppose I'm fine with keeping these separate. We should perhaps document that seconds_per_day is to be used to determine exactly that, while rotation_rate is to be used for dynamical computations and not to determine length of day (since you would need an additional parameter, length of year, to determine it).

**Comment by mcgibbon** [comment]
Can you revise HISTORY.rst with these changes, including putting the change to stefan_boltzmann name in breaking changes?

**Comment by JoyMonteiro** [comment]
Great, thanks. I think eventually I might write a utility function which takes orbital parameters and determines mean length of day, but this will help in the short term.

I will revise HISTORY and add it to this PR in the morning.

**Comment by mcgibbon** [comment]
Merging with PR #2.

**Pull request merged**
